# Generated by Django 4.2.5 on 2026-01-08 16:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ApiRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], default='GET', max_length=10)),
                ('path', models.CharField(help_text='Route path within the project, e.g. /users/list', max_length=255, validators=[django.core.validators.RegexValidator(message="Path must start with a '/'.", regex='^/'), django.core.validators.RegexValidator(message='Path cannot contain whitespace.', regex='^\\S+$')])),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('content_type', models.CharField(default='application/json', max_length=120)),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('response_file', models.FileField(blank=True, null=True, upload_to=server.models.route_upload_to)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='server.project')),
            ],
            options={
                'unique_together': {('project', 'method', 'path')},
            },
        ),
    ]
